# NO.1

In [44]:
import numpy as np
import pandas as pd

In [30]:
start_input = int(input("masukan nilai start: "))
end_input = int(input("masukan nilai end: "))

array = np.arange(start_input,end_input)
print(array)

masukan nilai start: 1
masukan nilai end: 28
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27]


In [33]:
array_2D = array.reshape(3,9)
array_2D

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27]])

In [47]:
array_3D = array.reshape(3,3,3)
array_3D

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

# NO.2

In [49]:
n_input = int(input("masukan nilai n: "))
start_input = int(input("masukan nilai start: "))
end_input = int(input("masukan nilai end: "))

array_random = np.random.randint(start_input,end_input,n_input)
array_random

masukan nilai n: 20
masukan nilai start: 1
masukan nilai end: 50


array([15,  5, 21, 16, 37, 47, 13, 27, 47, 16, 28, 30, 28,  8, 39,  8, 36,
       20, 46, 40])

In [51]:
array_random_2D = array_random.reshape(4,5)
array_random_2D

array([[15,  5, 21, 16, 37],
       [47, 13, 27, 47, 16],
       [28, 30, 28,  8, 39],
       [ 8, 36, 20, 46, 40]])

In [85]:
array_random_2D_tukarposisi = array_random_2D[:, ::-1]
array_random_2D_tukarposisi

array([[37, 16, 21,  5, 15],
       [16, 47, 27, 13, 47],
       [39,  8, 28, 30, 28],
       [40, 46, 20, 36,  8]])

In [52]:
array_random_3D = array_random.reshape(2,2,5)
array_random_3D

array([[[15,  5, 21, 16, 37],
        [47, 13, 27, 47, 16]],

       [[28, 30, 28,  8, 39],
        [ 8, 36, 20, 46, 40]]])

# NO.3

In [64]:
array = np.ones((10,10))*4
array

array([[4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.]])

In [65]:
array[1:-1,1:-1] = 0
array

array([[4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.]])

In [82]:
array1 = np.zeros((10,10))
array1[0,:] = 4
array1[:,0] = 4
array1[-1,:]= 4
array1[:,-1]= 4
array1

array([[4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.]])

In [80]:
array1[0,:] = 4
array1[:,0] = 4
array1[-1,:]= 4
array1[:,-1]= 4

In [81]:
array1

array([[4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.]])