In [1]:
import numpy as np

In [2]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [3]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [5]:
print(a[0])

[1 2 3 4]


In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [13]:
np.empty(6)

array([0.0e+000, 1.5e-323, 0.0e+000, 0.0e+000, 0.0e+000, 0.0e+000])

In [14]:
np.arange(2,20,3)

array([ 2,  5,  8, 11, 14, 17])

In [15]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [16]:
np.append(arr, [8,9])

array([1, 2, 3, 4, 5, 6, 7, 8, 8, 9])

In [17]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]]])

In [19]:
print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [20]:
array_example.ndim

3

In [21]:
array_example.size

24

In [22]:
array_example.shape

(3, 2, 4)

In [26]:
a = np.arange(6)
b = a.reshape(3,2)

print("a = ",a)
print("b = ",b)

a =  [0 1 2 3 4 5]
b =  [[0 1]
 [2 3]
 [4 5]]


In [27]:
c = np.array([1, 2, 3, 4, 5, 6])
c.shape

(6,)

In [28]:
c2 = c[np.newaxis]

In [30]:
c2
c2.shape

(1, 6)

In [32]:
c.shape

(6,)

In [33]:
print(c)
print(c2)

[1 2 3 4 5 6]
[[1 2 3 4 5 6]]


In [34]:
row_vector = c[np.newaxis, :]
print(row_vector.shape)
print(row_vector)

(1, 6)
[[1 2 3 4 5 6]]


In [36]:
col_vector = c[:, np.newaxis]
print(col_vector.shape)
print(col_vector)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [38]:
col_vector2 = col_vector[:, np.newaxis]
print(col_vector2.shape)
print(col_vector2)

(6, 1, 1)
[[[1]]

 [[2]]

 [[3]]

 [[4]]

 [[5]]

 [[6]]]


In [44]:
a = np.array([1, 2, 3, 4, 5, 6])

b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [45]:
a.shape

(6,)

In [46]:
b.shape

(6, 1)

In [47]:
c = np.expand_dims(a, axis=0)

In [48]:
c.shape

(1, 6)

In [50]:
print(a)
print(b)
print(c)

[1 2 3 4 5 6]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[[1 2 3 4 5 6]]


In [51]:
data = np.array([1,2,3])

print(data)
print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

[1 2 3]
1
2
[1 2]
[2 3]
[2 3]


In [52]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [53]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [57]:
print(a[a<=3])

[1 2 3]


In [59]:
print(a[a%2!=0])

[ 1  3  5  7  9 11]


In [60]:
a_1 = np.array([[1, 1],
                [2, 2]])

In [61]:
a_2 = np.array([[3, 3],
                [4, 4]])

In [63]:
a_2

array([[3, 3],
       [4, 4]])

In [64]:
np.vstack((a_1, a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [65]:
np.hstack((a_1, a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [67]:
a = np.array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
     [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [68]:
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [69]:
np.hsplit(a,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [70]:
A = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [71]:
A.sum()

4.8595784

In [72]:
A.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [73]:
A.min(axis=1)

array([0.17296777, 0.05093587, 0.12697628])

In [74]:
A.std()

0.21392120766089617

In [78]:
z = np.random.random((5,5))

In [79]:
z

array([[0.32626274, 0.89675829, 0.52258205, 0.44703152, 0.38745873],
       [0.63117506, 0.18120723, 0.02147156, 0.37228071, 0.95033903],
       [0.95549636, 0.71354621, 0.77240681, 0.15749746, 0.66102544],
       [0.37858296, 0.11992511, 0.80140296, 0.24139297, 0.92099251],
       [0.47943109, 0.03898961, 0.01104112, 0.05493546, 0.59683062]])

In [80]:
y = np.ones((5,5))

In [81]:
y

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [82]:
print(y+z)

[[1.32626274 1.89675829 1.52258205 1.44703152 1.38745873]
 [1.63117506 1.18120723 1.02147156 1.37228071 1.95033903]
 [1.95549636 1.71354621 1.77240681 1.15749746 1.66102544]
 [1.37858296 1.11992511 1.80140296 1.24139297 1.92099251]
 [1.47943109 1.03898961 1.01104112 1.05493546 1.59683062]]


In [83]:
x = np.random.random((5,5))

In [84]:
np.dot(x,z)

array([[0.85563342, 0.5128511 , 0.71535081, 0.36572443, 1.10458222],
       [0.81880041, 0.41137587, 0.39025116, 0.33809017, 1.119427  ],
       [1.41109535, 0.72844534, 1.0510119 , 0.64099843, 2.04120191],
       [1.20372061, 0.825339  , 0.68457363, 0.52562604, 1.4371097 ],
       [1.29403746, 0.93782703, 0.86724701, 0.44318848, 1.29638578]])

In [85]:
x*z

array([[0.03708707, 0.35484576, 0.21001673, 0.18766935, 0.02089919],
       [0.17737902, 0.05007256, 0.00152118, 0.08057486, 0.79896956],
       [0.29363794, 0.43482424, 0.23930819, 0.12388436, 0.45827918],
       [0.17533109, 0.05930657, 0.31032947, 0.03785298, 0.59766492],
       [0.15540872, 0.01352446, 0.00861589, 0.00571794, 0.22945316]])

In [86]:
data = np.array([[1, 2], [3, 4], [5, 6]])


In [87]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [99]:
data[2,1]

6

In [93]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [100]:
print(data.T)

[[1 3 5]
 [2 4 6]]


In [101]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [102]:
ndarr = np.array([[[1, 2], [3, 4]],
                  [[5, 6], [7, 8]]])

print(ndarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [103]:
arrflat = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [104]:
arrflat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [106]:
arrflat_2 = arrflat.flatten()

In [108]:
arrflat_2.shape

(12,)